config/routes.rb
Rails.application.routes.draw do

  root 'documents#index'

  resources :documents do 
    collection do 
      get :search
    end 
  end

end

app/models/document.rb
class Document < ActiveRecord::Base

  include PgSearch
  pg_search_scope :search, against: {
    title: 'A',
    body: 'B'
  },  using: {tsearch: {dictionary: 'english'}}

  # make urls seo friendly
  def to_param
    "#{id}-#{self.title.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/search?query
  def search
    @documents = Document.search(search_params[:query])
    render :index
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :body)
    end

    def search_params
      params.permit(:query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= form_for @document, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'form-control'
  .form-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_area :body, :class => 'form-control', rows: 10
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), documents_path, :class => 'btn btn-default'

app/views/documents/edit.html.haml
- model_class = Document
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/documents/index.html.haml
- model_class = Document
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= form_tag search_documents_path, method: :get,
    class: 'form-inline' do 
  .form-group
    = text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Enter query.'
  = submit_tag 'Search', class: 'btn btn-primary'
%hr
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @documents.each do |document|
      %tr
        %td= link_to document.id, document_path(document)
        %td= link_to document.title, document
        %td= document.body.truncate(100)
        %td=l document.created_at, format: :short
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_document_path(document), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), document_path(document), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_document_path, :class => 'btn btn-primary'

app/views/documents/new.html.haml
- model_class = Document
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/documents/show.html.haml
- model_class = Document
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @document.title
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @document.body


= link_to t('.back', :default => t("helpers.links.back")), documents_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_document_path(@document), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), document_path(@document), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "DemoAcs"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'DemoAcs', root_path, class: 'navbar-brand'
        -#
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
              %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
        -#.col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    -#%footer.navbar-fixed-bottom
      .container
        %p &copy; Company 2014